#ifndef __CM_REGISTRY_FILTER_H__
#define __CM_REGISTRY_FILTER_H__

typedef struct _CM_REGISTRY_FILTER_CONTEXT CM_REGISTRY_FILTER_CONTEXT, *PCM_REGISTRY_FILTER_CONTEXT;

typedef struct _CM_REGISTRY_FILTER_CONTEXT {
  LARGE_INTEGER       Cookie;
  CONST CONFIG_TABLE* Config;
  CONST VOID*         Table;
  PNPAGED_LOOKASIDE_LIST StackStretchList;
  DRV_DELEGATE_ROUTINE DrvDelegateRoutine;
} CM_REGISTRY_FILTER_CONTEXT, *PCM_REGISTRY_FILTER_CONTEXT;

NTSTATUS UninitializeRegistryFilter(PCM_REGISTRY_FILTER_CONTEXT Context);

NTSTATUS InitializeRegistryFilter(PDRIVER_OBJECT DrvObj, WCHAR Altitude[8],
  PNPAGED_LOOKASIDE_LIST LookAsideList, CONST CONFIG_TABLE* Config,
  CONST VOID* Table, DRV_DELEGATE_ROUTINE DrvDelegateRoutine,
  PCM_REGISTRY_FILTER_CONTEXT* Filter);

#endif // !__CM_REGISTRY_FILTER_H__