#ifndef __MACRO_H__
#define __MACRO_H__

typedef VOID NTAPI KNORMAL_ROUTINE(
  __in_opt PVOID NormalContext,
  __in_opt PVOID SystemArgument1,
  __in_opt PVOID SystemArgument2);

typedef KNORMAL_ROUTINE *PKNORMAL_ROUTINE;

enum UserCallBackRoutine {
  USER_CALLBACK_ROUTINE_BASE = 0,
  USER_CALLBACK_ROUTINE_IMAGE_BASE = 1,
  USER_CALLBACK_ROUTINE_CONFIG = 2,
  USER_CALLBACK_ROUTINE_TEST = 3,
  USER_CALLBACK_ROUTINE_SELF = 4,
  USER_CALLBACK_ROUTINE_MAX_VAILD = 16
};

#define INTERNAL_LUA_SCRIPT_TEST      0
#define INTERNAL_LUA_SCRIPT_UPDATE    1
#define INTERNAL_LUA_SCRIPT_LAUNCHER  2

#define USER_CALLBACK_ROUTINE_UNMAP   ((PVOID)~0)
#define USER_CALLBACK_ROUTINE_FREE    ((PVOID)((ULONG_PTR)~0 - 1))


#define UPDATE_CONFIG_MAX_SIZE    (16*1024)

#define LOOK_SIDE_ENTRY_MAX_SIZE    1024

EXTERN_C USHORT *NtBuildNumber;
#define MALLOC(size)    ExAllocatePoolWithTag(*NtBuildNumber >= 9600 ? NonPagedPoolNx : NonPagedPool, (size), LINE_NUMBER)

#define STORE_VALUE_NAME  L"STORE"

#define DRV_DELEGATE_NOT_RULE           1
#define DRV_DELEGATE_NOT_WHITE          2
#define DRV_DELEGATE_CAPTURE_CSRSS1     3
#define DRV_DELEGATE_CAPTURE_CSRSS2     4
#define DRV_DELEGATE_SXS_TIME_VALUE     5

typedef BOOLEAN (*DRV_DELEGATE_ROUTINE)(ULONG_PTR Delegate, PVOID Ctx, ULONGLONG ProcessHash, ULONGLONG KeyHash);

#define CONFIG_GLOBAL_INDEX_CONFIG      0

#define CONFIG_LOCAL_INDEX_WHITE        0
#define CONFIG_LOCAL_INDEX_UPDATE       1
#define CONFIG_LOCAL_INDEX_UPDATE_FIRST 2
#define CONFIG_LOCAL_INDEX_UPDATE_FAILE 3
#define CONFIG_LOCAL_INDEX_UPDATE_FORCE 4
#define CONFIG_LOCAL_INDEX_DRV_SET_UNLOAD 5
#define CONFIG_LOCAL_INDEX_DRV_FLAGS    6
#define CONFIG_LOCAL_INDEX_CSRSS_HASH    7

#define CONFIG_LOCAL_INDEX_WHITE_FLAGS  1

#define WHITE_FLAG_IGNORE_GLOBAL        0x0001
#define WHITE_FLAG_INVERSE_LOCAL        0x0002

#define DRV_FLAGS_RESTORE_REGISTRY      0x0001
#define DRV_FLAGS_HIDE_MAPFILE          0x0002
#define DRV_FLAGS_REPAIR_COMMAND        0x0004
#define DRV_FLAGS_HIDE_MAPFILE2         0x0008

#endif // !__MACRO_H__